name: General CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  trigger_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Checkout Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: checkout-event
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}

  trigger_node_build:
    runs-on: ubuntu-latest
    needs: trigger_checkout
    steps:
      - name: Trigger Node Build Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: node-build-event
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}

  trigger_docker_build:
    runs-on: ubuntu-latest
    needs: trigger_node_build
    steps:
      - name: Trigger Docker Build Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: docker-build-event
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}

  trigger_docker_push:
    runs-on: ubuntu-latest
    needs: trigger_docker_build
    steps:
      - name: Trigger Docker Push Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: docker-push-event
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}
